name: Publish Library

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Test with Gradle
      run: ./gradlew test
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## IsoSocket v${{ github.ref_name }}
          
          ### Features
          - Dual Engine Support (Blocking and Non-blocking I/O)
          - TLS/SSL Support with certificate pinning
          - Automatic reconnection with exponential backoff
          - Connection state management
          - API 21+ support
          - Thread-safe design
          
          ### Installation
          ```gradle
          implementation 'com.github.Miaadrajabi:IsoSocket:${{ github.ref_name }}'
          ```
          
          ### Quick Start
          ```java
          TcpClient client = new TcpClient.Builder()
              .host("example.com")
              .port(8080)
              .build();
              
          client.connect();
          TcpResponse response = client.sendAndReceive("Hello".getBytes(), 5000);
          client.close();
          ```
        draft: false
        prerelease: false
